apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma-deployment
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - image: louislam/uptime-kuma:1
          imagePullPolicy: IfNotPresent
          name: uptime-kuma-app
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: kuma-data
      spec:
        accessModes: ["ReadWriteOnce"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  type: ClusterIP
  selector:
    app: uptime-kuma
  ports:
    - port: 80
      targetPort: 3001
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "uptime.imagdic.me"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-service
                port:
                  number: 80