apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami-deployment
spec:
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - image: ghcr.io/umami-software/umami:postgresql-latest
          imagePullPolicy: IfNotPresent
          name: umami-app
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: umami-connection-string
                  optional: false
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: umami-service
spec:
  type: ClusterIP
  selector:
    app: umami
  ports:
    - port: 80
      targetPort: 3000
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "analytics.imagdic.me"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: umami-service
                port:
                  number: 80